Replace pre-commit in CI with prek

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -13,27 +13,32 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
-      - uses: actions/setup-python@v6.1.0
-        with:
-          python-version: '3.12'
       - uses: actions/setup-dotnet@v5.0.1
         with:
           dotnet-version: '8.0.x'
-      - name: Install pre-commit
-        run: python -m pip install pre-commit
+      - uses: actions/setup-go@v6  # One of our hooks (gitleaks) needs a newer Go version than we get from the runner
+        with:
+          go-version: '>=1.25.4'
+          cache: false
+      - name: Install uv
+        uses: astral-sh/setup-uv@v7
+        with:
+          enable-cache: "false"
+      - name: Install prek
+        run: uv tool install prek
         shell: bash
       - name: Cache pre-commit environments
         uses: actions/cache@v5
         with:
-          path: ~/.cache/pre-commit
-          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
-      - name: Setup pre-commit environments
-        run: pre-commit run
-      - name: Run pre-commit dotnet-format, with retries
+          path: ~/.cache/prek
+          key: prek|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
+      - name: Setup prek environments (separate step for timing purposes)
+        run: prek run
+      - name: Run prek dotnet-format, with retries
         uses: Wandalen/wretry.action@v3
         with:
-          command: pre-commit run dotnet-format --show-diff-on-failure --color=always --all-files || { git checkout -- . ; exit 1 ; }  # In case dotnet-format fails, reset the changes it made. This way, we can differentiate between a NuGet failure and a real formatting issue
-      - name: Remove dotnet-format from the list of pre-commit jobs to run (since we already ran it)
+          command: prek run dotnet-format --show-diff-on-failure --color=always --all-files || { git checkout -- . ; exit 1 ; }  # In case dotnet-format fails, reset the changes it made. This way, we can differentiate between a NuGet failure and a real formatting issue
+      - name: Remove dotnet-format from the list of prek jobs to run (since we already ran it)
         run: yq eval 'del(.repos[] | select(.hooks[].id == "dotnet-format"))' -i .pre-commit-config.yaml
       - name: Run the rest of pre-commit
-        run: pre-commit run --show-diff-on-failure --color=always --all-files
+        run: prek run --show-diff-on-failure --color=always --all-files
